<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function getAll()
    {
        return $this->createQueryBuilder('r')
            ->innerJoin('r.user', 'u')
            ->select('u.email, r.name, r.edrpou, r.file, r.nreg, r.publicDt')
            ->orderBy('r.publicDt', 'DESC')
            ->getQuery()
            ->getResult();
    }
}
